version: '2'

services:
  db:
    image: mysql:latest
    container_name: db2
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - ./luna_db:/var/lib/mysql
