# Generated by Django 5.0.4 on 2024-04-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_luna', '0002_banco_caja_categoria_ciudad_cliente_clientecontacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nombre_rol',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
