# Generated by Django 5.0.4 on 2024-04-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_luna', '0004_profile_created_at_profile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
